### ISSUE TITLE
About Your Project

### ISSUE THREAD

**Issue by Raxana7** [Pi769/Steam-Account-Checker#1]
Your project looks like good. 
I waiting a file uploader for multiple accounts :)
It would be nice to continue doing.
Have a nice work.

**Comment by Pi769** [comment]
I am still working on a file uploader which can help with multi accounts. This is actually my first time using JavaScript, I usually do everything I can in python. So right now I am trying my best to read and document how to handle file uploads.

My private build has a working uploader as you can see in the photo below. The difficult part is actually passing everything through the webapp. Without me downloading the accounts, because I am not interested in stealing any accounts.
![YdjcikhR1B](https://user-images.githubusercontent.com/41908416/79540275-77c6a180-80ba-11ea-8442-b735b9db1ce5.png)

If I'd have to give you an expected time till completion. It would be 2-6 days as I am quite busy with other private projects.

**Comment by Raxana7** [comment]
I am not interested in stealing any accounts too. I am not stealing any accounts with using this tools :)
